import arcade

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Michal Oracki - Interactive radar"

CENTER_X = SCREEN_WIDTH // 2
CENTER_Y = SCREEN_HEIGHT // 2
RADIANS_PER_FRAME = 0.04
RADAR_RANGE = 1.0 # in radians
DEFAULT_PERCENTAGE_VALUE = 50
SWEEP_LENGTH = 250
RADAR_REFRESH_TIME = 2.0

MINIMAP_BACKGROUND_COLOR = arcade.get_four_byte_color(arcade.color.DARK_SLATE_GRAY)
MINIMAP_RATIO = 5
MAP_WIDTH = SCREEN_WIDTH
MAP_HEIGHT = SCREEN_HEIGHT

NUMBER_OF_SHAPES = 20
OBJECTS_DEFAULT_SPEED = 1

INIT_WAVE_RADIUS = SWEEP_LENGTH // 25